name: todo_gazelle 
description: A new Gazelle project.
version: 0.1.0

environment:
  sdk: ^3.4.3

dependencies:
  gazelle_core: ^0.3.0
  uid: ^0.0.2

dev_dependencies:
  lints: ">=2.1.0 <4.0.0"
  test: ^1.24.0

gazelle:
